services:
  - type: web
    name: flask-message-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn database:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0